theme: minima
title: Python
author: Luis_Hdz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I start learning how to programm in python after several years of looking what i want to learn, 
 the first thing i mean interesting was cybersecurity, buy with the time python speack to me and here i am
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
